// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright (C) Stompy Robot LTD 2019")]
[assembly: AssemblyCompanyAttribute("Stompy Robot LTD")]
[assembly: AssemblyVersionAttribute("1.5.0")]
[assembly: AssemblyInformationalVersionAttribute("1.5.0-pre")]
[assembly: AssemblyFileVersionAttribute("1.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.5.0";
    }
}
